export const categoryConstants = {
    GET_CATEGORY: 'GET_CATEGORY',
    REQUEST_CATEGORY: 'REQUEST_CATEGORY',
    ADD_CATEGORY: 'ADD_CATEGORY',
    DELETE_CATEGORY: 'DELETE_CATEGORY',
    UPDATE_CATEGORY: 'UPDATE_CATEGORY',
};