export const pizzaConstants = {
    ADD_PIZZA: 'ADD_PIZZA',
    GET_ALL_PIZZAS: 'GET_ALL_PIZZAS',
    GET_SINGLE_PIZZA: 'GET_SINGLE_PIZZA',
    UPDATE_PIZZA: 'UPDATE_PIZZA',
    DELETE_PIZZA: 'DELETE_PIZZA',
    PIZZA_REQUEST: 'PIZZA_REQUEST',
};